### ISSUE TITLE
Change all console.log to ErrorHelper 

### ISSUE THREAD

**Issue by aoehmichen** [dsi-icl/OPAL-Cache#8]
https://github.com/dsi-icl/OPAL-Cache/blob/e4196a355588673fd737eb712b8b415f8f1e2d0a/src/cacheController.js#L59
const { ErrorHelper, Constants, DataModels } = require('eae-utils');

            res.status(500);
            res.json(ErrorHelper('Internal Mongo Error', error));

**Comment by emalgorithm** [comment]
Solved
